# Generated by Django 4.1.3 on 2022-12-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_rename_added_by_movie_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="user",
            new_name="added_by",
        ),
    ]
