# Generated by Django 4.1.3 on 2022-12-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_rename_user_movie_added_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="added_by",
            new_name="user",
        ),
    ]
